3 exercises are done
js-tasks-ru/js-20221021_bomzuan pull request #1
Opened 2022-10-27 16:35 UTC by YevBor

2022-10-27 16:35 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2022-10-28 16:27 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return (param === 'asc') ? newSortedArray: newSortedArray.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-10-28 16:28 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
good 👍

2022-10-28 16:28 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  arrFromObject.forEach(([key,value]) =>{
good 👍

2022-10-28 16:28 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-10-29 12:22 UTC, YevBor commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return (param === 'asc') ? newSortedArray: newSortedArray.reverse();
Done

2022-10-29 12:24 UTC, YevBor commented
Внес все правки

2022-10-31 10:06 UTC, dosandk approved these changes
good 👍

2022-10-31 10:07 UTC, merged